// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDPGoHAgt5U1kYCB7nCpXkSx1mXit_9Mw',
    appId: '1:1055042521734:web:23f817004ec9e9a7259f07',
    messagingSenderId: '1055042521734',
    projectId: 'flutterfirebaseapp-45730',
    authDomain: 'flutterfirebaseapp-45730.firebaseapp.com',
    storageBucket: 'flutterfirebaseapp-45730.appspot.com',
    measurementId: 'G-X6ZSEYJENL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiHKQzmGwTbD5KwGtvNYkbYPb0R1xm0dQ',
    appId: '1:1055042521734:android:285535afdab1dcfc259f07',
    messagingSenderId: '1055042521734',
    projectId: 'flutterfirebaseapp-45730',
    storageBucket: 'flutterfirebaseapp-45730.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJVYfNGqClEufm7eYu7kkdbm_ToPGtbE',
    appId: '1:1055042521734:ios:65964aa18e2a6afb259f07',
    messagingSenderId: '1055042521734',
    projectId: 'flutterfirebaseapp-45730',
    storageBucket: 'flutterfirebaseapp-45730.appspot.com',
    iosClientId: '1055042521734-q3u33l24c7v031v9c7alcv29lo1jh9lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJVYfNGqClEufm7eYu7kkdbm_ToPGtbE',
    appId: '1:1055042521734:ios:b3388ffbd7007b1d259f07',
    messagingSenderId: '1055042521734',
    projectId: 'flutterfirebaseapp-45730',
    storageBucket: 'flutterfirebaseapp-45730.appspot.com',
    iosClientId: '1055042521734-n4irt8pg16mckg67s04pejtgj4gd3s7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp.RunnerTests',
  );
}
